chore: Update codeql
Signed-off-by: Steve Hipwell <steve.hipwell@gmail.com>

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -84,8 +84,12 @@ jobs:
 
       - name: Check diff
         run: |
-          git diff --compact-summary --exit-code || \
-            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
+          set -euo pipefail
+
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error::Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."
+            exit 1
+          fi
 
   matrix:
     name: Matrix
@@ -142,13 +146,22 @@ jobs:
           terraform_version: ${{ matrix.tf_version }}
           terraform_wrapper: false
 
+      - name: Terraform Path
+        id: tf
+        run: |
+          set -euo pipefail
+
+          echo "path=$(command -v terraform || true)" >> "${GITHUB_OUTPUT}"
+
       - name: Go mod download
         run: go mod download
 
       - name: Test
         env:
           TF_ACC: "1"
+          TF_ACC_PROVIDER_NAMESPACE: terr4m
           TF_ACC_TERRAFORM_VERSION: ${{ matrix.tf_version }}
+          TF_ACC_TERRAFORM_PATH: ${{ steps.tf.outputs.path }}
         run: go test -v -timeout 120m -cover ./...
 
   check:
